// frontend/src/Ontoorub/Rubbish/views/Home.tsx
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import {
  ArrowRight, Upload, FileText, Database, Zap, Globe,
  MessageSquare, Users, BarChart3, TrendingUp, Clock,
  ChevronDown, Star, Github, ExternalLink, Play
} from 'lucide-react';
import { cn } from '@/utils/cn';

// Import components
import HistoryDatabase from '@/components/ontology/HistoryDatabase';

// Import APIs
import { graphApi } from '@/api/ontology';

export default function Home() {
  const navigate = useNavigate();

  // Form data
  const [simulationRequirement, setSimulationRequirement] = useState('');
  const [files, setFiles] = useState<File[]>([]);
  
  // Status
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [isDragOver, setIsDragOver] = useState(false);

  // File input reference
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Computed property: can submit
  const canSubmit = useMemo(() => {
    return simulationRequirement.trim() !== '' && files.length > 0;
  }, [simulationRequirement, files]);

  // Trigger file selection
  const triggerFileInput = () => {
    if (!loading) {
      fileInputRef.current?.click();
    }
  };

  // Handle file selection
  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFiles = Array.from(event.target.files || []);
    addFiles(selectedFiles);
  };

  // Handle drag & drop
  const handleDragOver = (e: React.DragEvent) => {
    if (!loading) {
      setIsDragOver(true);
    }
  };

  const handleDragLeave = (e: React.DragEvent) => {
    setIsDragOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    setIsDragOver(false);
    if (loading) return;
    
    const droppedFiles = Array.from(e.dataTransfer.files);
    addFiles(droppedFiles);
  };

  // Add files
  const addFiles = (newFiles: File[]) => {
    const validFiles = newFiles.filter(file => {
      const ext = file.name.split('.').pop()?.toLowerCase();
      return ['pdf', 'md', 'txt'].includes(ext || '');
    });
    setFiles(prev => [...prev, ...validFiles]);
  };

  // Remove file
  const removeFile = (index: number) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  // Scroll to bottom
  const scrollToBottom = () => {
    window.scrollTo({
      top: document.body.scrollHeight,
      behavior: 'smooth'
    });
  };

  // Start simulation
  const startSimulation = async () => {
    if (!canSubmit || loading) return;
    
    setLoading(true);
    setError('');
    
    try {
      // Create FormData for file upload
      const formData = new FormData();
      files.forEach(file => {
        formData.append('files', file);
      });
      formData.append('simulation_requirement', simulationRequirement);

      // Generate ontology first
      const ontologyRes = await graphApi.generateOntology(formData);
      if (ontologyRes.data.success) {
        const taskId = ontologyRes.data.data.task_id;
        
        // Create project
        const projectRes = await graphApi.buildGraph({
          project_id: taskId,
          chunk_size: 1000,
          chunk_overlap: 200
        });
        
        if (projectRes.data.success) {
          // Navigate to main view with the new project
          navigate(`/ontology/main/${taskId}`);
        }
      }
    } catch (err) {
      console.error('Failed to start simulation:', err);
      setError('Failed to start simulation. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const workflowSteps = [
    {
      num: '01',
      title: 'Knowledge Graph Construction',
      desc: 'Reality Seed Extraction & Individual/Collective Memory Injection & GraphRAG Construction'
    },
    {
      num: '02',
      title: 'Environment Setup',
      desc: 'Entity Relationship Extraction & Persona Generation & Environment Config with Realistic Parameters'
    },
    {
      num: '03',
      title: 'Start Simulation',
      desc: 'Dual-Platform Parallel Simulation & Auto-Analysis of Prediction Needs & Dynamic Timeline Memory Updates'
    },
    {
      num: '04',
      title: 'Report Generation',
      desc: 'ReportAgent with Rich Toolset for Deep Interaction with Post-Simulation Environment'
    },
    {
      num: '05',
      title: 'Deep Interaction',
      desc: 'Chat with Anyone in the Simulated World & Converse with ReportAgent'
    }
  ];

  return (
    <div className="home-container min-h-screen bg-[#090B10] text-white">
      {/* Top Navigation Bar */}
      <nav className="navbar h-16 bg-black border-b border-white/10 flex items-center justify-between px-8">
        <div className="nav-brand text-xl font-black tracking-wider">aarambh</div>
        <div className="nav-links">
          <a 
            href="https://github.com/666ghj/aarambh" 
            target="_blank" 
            rel="noopener noreferrer"
            className="github-link flex items-center gap-2 text-white/80 hover:text-white transition-colors text-sm font-medium"
          >
            Visit our GitHub <ExternalLink className="w-4 h-4" />
          </a>
        </div>
      </nav>

      <div className="main-content max-w-7xl mx-auto px-8 py-16">
        {/* Upper Section: Hero Area */}
        <section className="hero-section flex justify-between items-center mb-20">
          <div className="hero-left flex-1 pr-16">
            <div className="tag-row flex items-center gap-4 mb-6">
              <span className="orange-tag bg-[var(--accent)] text-[#07080C] px-3 py-1 text-xs font-black tracking-wider rounded">
                Simple & Universal Collective Intelligence Engine
              </span>
              <span className="version-text text-white/60 text-sm font-medium">/ v0.1-Preview</span>
            </div>
            
            <h1 className="main-title text-6xl font-black leading-tight mb-8 tracking-tight">
              Upload Any Report<br />
              <span className="gradient-text bg-gradient-to-r from-white to-white/60 bg-clip-text text-transparent">
                Instantly Predict the Future
              </span>
            </h1>
            
            <div className="hero-desc text-lg leading-relaxed text-white/70 max-w-2xl mb-12">
              <p className="mb-6">
                Even with just a piece of text, <span className="highlight-bold font-black text-white">aarambh</span> can automatically generate a parallel world composed of up to <span className="highlight-orange text-[var(--accent)] font-black">millions of Agents</span> based on the reality seeds within it. Through a god's-eye view injection of variables, finding <span className="highlight-code bg-white/10 px-2 py-1 rounded font-mono text-sm text-white">"local optimal solutions"</span> in complex group interactions within dynamic environments
              </p>
              <p className="slogan-text text-xl font-black text-white leading-relaxed border-l-4 border-[var(--accent)] pl-6">
                Let the future rehearse among Agents, let decisions prevail after a hundred battles<span className="blinking-cursor text-[var(--accent)] animate-pulse">_</span>
              </p>
            </div>
             
            <div className="decoration-square w-4 h-4 bg-[var(--accent)]"></div>
          </div>
          
          <div className="hero-right flex-0.8 flex flex-col justify-between items-end">
            {/* Logo Area */}
            <div className="logo-container w-full flex justify-end pr-10">
              <img src="/logo.png" alt="Aarambh Logo" className="hero-logo max-w-md w-full" />
            </div>
            
            <button 
              onClick={scrollToBottom}
              className="scroll-down-btn w-12 h-12 border border-white/20 bg-transparent flex items-center justify-center cursor-pointer text-[var(--accent)] text-2xl transition-all hover:border-[var(--accent)] rounded-xl"
            >
              <ChevronDown />
            </button>
          </div>
        </section>

        {/* Lower Section: Two-Column Layout */}
        <section className="dashboard-section flex gap-16 border-t border-white/10 pt-16">
          {/* Left Panel: Status & Steps */}
          <div className="left-panel flex-0.8">
            <div className="panel-header flex items-center gap-2 mb-6">
              <span className="status-dot text-[var(--accent)]">■</span>
              <span className="text-white/60 font-mono text-sm">System Status</span>
            </div>
            
            <h2 className="section-title text-4xl font-black mb-4">Ready to Go</h2>
            <p className="section-desc text-white/70 mb-8 leading-relaxed">
              Prediction engine standing by, upload multiple unstructured data files to initialize simulation sequence
            </p>
            
            {/* Data Metric Cards */}
            <div className="metrics-row flex gap-5 mb-8">
              <div className="metric-card border border-white/10 p-6 min-w-[150px] bg-white/5">
                <div className="metric-value font-mono text-2xl font-black mb-2">Low Cost</div>
                <div className="metric-label text-xs text-white/60">Avg $5/simulation</div>
              </div>
              <div className="metric-card border border-white/10 p-6 min-w-[150px] bg-white/5">
                <div className="metric-value font-mono text-2xl font-black mb-2">High Availability</div>
                <div className="metric-label text-xs text-white/60">Up to Million-Agent Simulation</div>
              </div>
            </div>

            {/* Project Simulation Steps */}
            <div className="steps-container border border-white/10 p-8 bg-white/5">
              <div className="steps-header flex items-center gap-2 mb-8">
                <span className="diamond-icon text-xl">◆</span>
                <span className="text-white/60 font-mono text-sm">Workflow Sequence</span>
              </div>
              <div className="workflow-list flex flex-col gap-6">
                {workflowSteps.map((step, index) => (
                  <div key={index} className="workflow-item flex items-start gap-5">
                    <span className="step-num font-mono font-black text-white/30 text-lg">{step.num}</span>
                    <div className="step-info flex-1">
                      <div className="step-title font-black text-lg mb-2">{step.title}</div>
                      <div className="step-desc text-sm text-white/60 leading-relaxed">{step.desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Panel: Interaction Console */}
          <div className="right-panel flex-1.2">
            <div className="console-box border border-white/20 p-2 bg-black/50">
              {/* Upload Area */}
              <div className="console-section p-6">
                <div className="console-header flex justify-between items-center mb-4">
                  <span className="console-label font-mono text-xs text-white/60">01 / Reality Seed</span>
                  <span className="console-meta font-mono text-xs text-white/40">Formats: PDF, MD, TXT</span>
                </div>
                
                <div 
                  className={cn(
                    "upload-zone border-2 border-dashed h-48 overflow-y-auto flex items-center justify-center cursor-pointer transition-all bg-white/5",
                    isDragOver ? "border-[var(--accent)] bg-[var(--accent)]/10" : "border-white/20 hover:border-white/40 hover:bg-white/10",
                    files.length > 0 && "items-start"
                  )}
                  onDragOver={handleDragOver}
                  onDragLeave={handleDragLeave}
                  onDrop={handleDrop}
                  onClick={triggerFileInput}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    accept=".pdf,.md,.txt"
                    onChange={handleFileSelect}
                    style={{ display: 'none' }}
                    disabled={loading}
                  />
                  
                  {files.length === 0 ? (
                    <div className="upload-placeholder text-center">
                      <div className="upload-icon w-12 h-12 border border-white/20 flex items-center justify-center mx-auto mb-4 text-white/40">
                        <Upload className="w-6 h-6" />
                      </div>
                      <div className="upload-title font-medium text-white mb-2">Drag & Drop Files</div>
                      <div className="upload-hint font-mono text-xs text-white/40">Or click to browse</div>
                    </div>
                  ) : (
                    <div className="file-list w-full p-4 flex flex-col gap-3">
                      {files.map((file, index) => (
                        <div key={index} className="file-item flex items-center bg-black/50 p-3 rounded-lg border border-white/10 font-mono text-sm">
                          <span className="file-icon mr-3">📄</span>
                          <span className="file-name flex-1 text-white/80">{file.name}</span>
                          <button 
                            onClick={(e) => {
                              e.stopPropagation();
                              removeFile(index);
                            }}
                            className="remove-btn bg-none border-none cursor-pointer text-xl text-white/40 hover:text-white transition-colors"
                          >
                            ×
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              {/* Divider */}
              <div className="console-divider flex items-center my-4">
                <div className="flex-1 h-px bg-white/10"></div>
                <span className="px-4 font-mono text-xs text-white/30 uppercase tracking-wider">Input Parameters</span>
                <div className="flex-1 h-px bg-white/10"></div>
              </div>

              {/* Input Area */}
              <div className="console-section p-6">
                <div className="console-header mb-4">
                  <span className="console-label font-mono text-xs text-white/60">&gt;_ 02 / Simulation Prompt</span>
                </div>
                <div className="input-wrapper relative border border-white/20 bg-black/50">
                  <textarea
                    value={simulationRequirement}
                    onChange={(e) => setSimulationRequirement(e.target.value)}
                    className="code-input w-full border-none bg-transparent p-5 font-mono text-sm leading-relaxed resize-none outline-none min-h-[150px] text-white placeholder-white/30"
                    placeholder="// Enter simulation or prediction needs in natural language (e.g., What sentiment trend would emerge if Wuhan University announced revocation of disciplinary action for a student?)"
                    rows={6}
                    disabled={loading}
                  />
                  <div className="model-badge absolute bottom-3 right-3 font-mono text-xs text-white/30">
                    Engine: aarambh-V1.0
                  </div>
                </div>
              </div>

              {/* Launch Button */}
              <div className="console-section btn-section p-6 pt-0">
                <button 
                  className={cn(
                    "start-engine-btn w-full py-6 font-black text-lg flex justify-between items-center cursor-pointer transition-all tracking-wider relative overflow-hidden rounded-xl",
                    canSubmit && !loading 
                      ? "bg-[var(--accent)] text-[#07080C] hover:opacity-90 transform hover:-translate-y-1" 
                      : "bg-white/10 text-white/50 cursor-not-allowed"
                  )}
                  onClick={startSimulation}
                  disabled={!canSubmit || loading}
                >
                  <span>{loading ? 'Initializing...' : 'Launch Engine'}</span>
                  <span className="btn-arrow">
                    {loading ? (
                      <div className="animate-spin">
                        <Play className="w-5 h-5" />
                      </div>
                    ) : (
                      <ArrowRight className="w-5 h-5" />
                    )}
                  </span>
                </button>
              </div>
            </div>
          </div>
        </section>

        {/* History Project Database */}
        <HistoryDatabase />
      </div>

      {/* Error Overlay */}
      <AnimatePresence>
        {error && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="fixed bottom-8 right-8 bg-red-500/20 backdrop-blur-md border border-red-500/50 text-red-300 px-6 py-4 rounded-2xl max-w-md"
          >
            <div className="flex items-start gap-4">
              <div className="flex-1">
                <p className="text-sm font-medium mb-1">Error</p>
                <p className="text-xs opacity-80">{error}</p>
              </div>
              <button
                onClick={() => setError('')}
                className="text-red-400 hover:text-red-300 text-xl"
              >
                ×
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// frontend/public/ontology/src/views/Home.vue
﻿<template>
  <div class="home-container">
    <!-- Top Navigation Bar -->
    <nav class="navbar">
      <div class="nav-brand">aarambh</div>
      <div class="nav-links">
        <a href="https://github.com/666ghj/aarambh" target="_blank" class="github-link">
          Visit our GitHub <span class="arrow">â†—</span>
        </a>
      </div>
    </nav>

    <div class="main-content">
      <!-- Upper Section: Hero Area -->
      <section class="hero-section">
        <div class="hero-left">
          <div class="tag-row">
            <span class="orange-tag">Simple & Universal Collective Intelligence Engine</span>
            <span class="version-text">/ v0.1-Preview</span>
          </div>
          
          <h1 class="main-title">
            Upload Any Report<br>
            <span class="gradient-text">Instantly Predict the Future</span>
          </h1>
          
          <div class="hero-desc">
            <p>
              Even with just a piece of text, <span class="highlight-bold">aarambh</span> can automatically generate a parallel world composed of up to <span class="highlight-orange">millions of Agents</span> based on the reality seeds within it. Through a god's-eye view injection of variables, finding <span class="highlight-code">"local optimal solutions"</span> in complex group interactions within dynamic environments
            </p>
            <p class="slogan-text">
              Let the future rehearse among Agents, let decisions prevail after a hundred battles<span class="blinking-cursor">_</span>
            </p>
          </div>
           
          <div class="decoration-square"></div>
        </div>
        
        <div class="hero-right">
          <!-- Logo Area -->
          <div class="logo-container">
            <img src="/logo.png" alt="Aarambh Logo" class="hero-logo" />
          </div>
          
          <button class="scroll-down-btn" @click="scrollToBottom">
            â†“
          </button>
        </div>
      </section>

      <!-- Lower Section: Two-Column Layout -->
      <section class="dashboard-section">
        <!-- Left Panel: Status & Steps -->
        <div class="left-panel">
          <div class="panel-header">
            <span class="status-dot">â– </span> System Status
          </div>
          
          <h2 class="section-title">Ready to Go</h2>
          <p class="section-desc">
            Prediction engine standing by, upload multiple unstructured data files to initialize simulation sequence
          </p>
          
          <!-- Data Metric Cards -->
          <div class="metrics-row">
            <div class="metric-card">
              <div class="metric-value">Low Cost</div>
              <div class="metric-label">Avg $5/simulation</div>
            </div>
            <div class="metric-card">
              <div class="metric-value">High Availability</div>
              <div class="metric-label">Up to Million-Agent Simulation</div>
            </div>
          </div>

          <!-- Project Simulation Steps (New Section) -->
          <div class="steps-container">
            <div class="steps-header">
               <span class="diamond-icon">â—‡</span> Workflow Sequence
            </div>
            <div class="workflow-list">
              <div class="workflow-item">
                <span class="step-num">01</span>
                <div class="step-info">
                  <div class="step-title">Knowledge Graph Construction</div>
                  <div class="step-desc">Reality Seed Extraction & Individual/Collective Memory Injection & GraphRAG Construction</div>
                </div>
              </div>
              <div class="workflow-item">
                <span class="step-num">02</span>
                <div class="step-info">
                  <div class="step-title">Environment Setup</div>
                  <div class="step-desc">Entity Relationship Extraction & Persona Generation & Environment Config with Realistic Parameters</div>
                </div>
              </div>
              <div class="workflow-item">
                <span class="step-num">03</span>
                <div class="step-info">
                  <div class="step-title">Start Simulation</div>
                  <div class="step-desc">Dual-Platform Parallel Simulation & Auto-Analysis of Prediction Needs & Dynamic Timeline Memory Updates</div>
                </div>
              </div>
              <div class="workflow-item">
                <span class="step-num">04</span>
                <div class="step-info">
                  <div class="step-title">Report Generation</div>
                  <div class="step-desc">ReportAgent with Rich Toolset for Deep Interaction with Post-Simulation Environment</div>
                </div>
              </div>
              <div class="workflow-item">
                <span class="step-num">05</span>
                <div class="step-info">
                  <div class="step-title">Deep Interaction</div>
                  <div class="step-desc">Chat with Anyone in the Simulated World & Converse with ReportAgent</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Right Panel: Interaction Console -->
        <div class="right-panel">
          <div class="console-box">
            <!-- Upload Area -->
            <div class="console-section">
              <div class="console-header">
                <span class="console-label">01 / Reality Seed</span>
                <span class="console-meta">Formats: PDF, MD, TXT</span>
              </div>
              
              <div 
                class="upload-zone"
                :class="{ 'drag-over': isDragOver, 'has-files': files.length > 0 }"
                @dragover.prevent="handleDragOver"
                @dragleave.prevent="handleDragLeave"
                @drop.prevent="handleDrop"
                @click="triggerFileInput"
              >
                <input
                  ref="fileInput"
                  type="file"
                  multiple
                  accept=".pdf,.md,.txt"
                  @change="handleFileSelect"
                  style="display: none"
                  :disabled="loading"
                />
                
                <div v-if="files.length === 0" class="upload-placeholder">
                  <div class="upload-icon">â†‘</div>
                  <div class="upload-title">Drag & Drop Files</div>
                  <div class="upload-hint">Or click to browse</div>
                </div>
                
                <div v-else class="file-list">
                  <div v-for="(file, index) in files" :key="index" class="file-item">
                    <span class="file-icon">ðŸ“„</span>
                    <span class="file-name">{{ file.name }}</span>
                    <button @click.stop="removeFile(index)" class="remove-btn">Ã—</button>
                  </div>
                </div>
              </div>
            </div>

            <!-- Divider -->
            <div class="console-divider">
              <span>Input Parameters</span>
            </div>

            <!-- Input Area -->
            <div class="console-section">
              <div class="console-header">
                <span class="console-label">>_ 02 / Simulation Prompt</span>
              </div>
              <div class="input-wrapper">
                <textarea
                  v-model="formData.simulationRequirement"
                  class="code-input"
                  placeholder="// Enter simulation or prediction needs in natural language (e.g., What sentiment trend would emerge if Wuhan University announced revocation of disciplinary action for a student?)"
                  rows="6"
                  :disabled="loading"
                ></textarea>
                <div class="model-badge">Engine: aarambh-V1.0</div>
              </div>
            </div>

            <!-- Launch Button -->
            <div class="console-section btn-section">
              <button 
                class="start-engine-btn"
                @click="startSimulation"
                :disabled="!canSubmit || loading"
              >
                <span v-if="!loading">Launch Engine</span>
                <span v-else>Initializing...</span>
                <span class="btn-arrow">â†’</span>
              </button>
            </div>
          </div>
        </div>
      </section>

      <!-- History Project Database -->
      <HistoryDatabase />
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import HistoryDatabase from '../components/HistoryDatabase.vue'

const router = useRouter()

// Form data
const formData = ref({
  simulationRequirement: ''
})

// File list
const files = ref([])

// Status
const loading = ref(false)
const error = ref('')
const isDragOver = ref(false)

// File input reference
const fileInput = ref(null)

// Computed property: can submit
const canSubmit = computed(() => {
  return formData.value.simulationRequirement.trim() !== '' && files.value.length > 0
})

// Trigger file selection
const triggerFileInput = () => {
  if (!loading.value) {
    fileInput.value?.click()
  }
}

// Handle file selection
const handleFileSelect = (event) => {
  const selectedFiles = Array.from(event.target.files)
  addFiles(selectedFiles)
}

// Handle drag & drop
const handleDragOver = (e) => {
  if (!loading.value) {
    isDragOver.value = true
  }
}

const handleDragLeave = (e) => {
  isDragOver.value = false
}

const handleDrop = (e) => {
  isDragOver.value = false
  if (loading.value) return
  
  const droppedFiles = Array.from(e.dataTransfer.files)
  addFiles(droppedFiles)
}

// Add files
const addFiles = (newFiles) => {
  const validFiles = newFiles.filter(file => {
    const ext = file.name.split('.').pop().toLowerCase()
    return ['pdf', 'md', 'txt'].includes(ext)
  })
  files.value.push(...validFiles)
}

// Remove file
const removeFile = (index) => {
  files.value.splice(index, 1)
}

// Scroll to bottom
const scrollToBottom = () => {
  window.scrollTo({
    top: document.body.scrollHeight,
    behavior: 'smooth'
  })
}

// Start simulation - jump immediately, API calls handled in Process page
const startSimulation = () => {
  if (!canSubmit.value || loading.value) return
  
  // Store data for upload
  import('../store/pendingUpload.js').then(({ setPendingUpload }) => {
    setPendingUpload(files.value, formData.value.simulationRequirement)
    
    // Jump to Process page (using special flag for new project)
    router.push({
      name: 'Process',
      params: { projectId: 'new' }
    })
  })
}
</script>

<style scoped>
/* Global Variables & Reset */
:root {
  --black: #000000;
  --white: #FFFFFF;
  --orange: #FF4500;
  --gray-light: #F5F5F5;
  --gray-text: #666666;
  --border: #E5E5E5;
  /* 
    Use Space Grotesk as main heading font, JetBrains Mono as code/label font
    Ensure these Google Fonts are imported in index.html
  */
  --font-mono: 'JetBrains Mono', monospace;
  --font-sans: 'Space Grotesk', 'Noto Sans SC', system-ui, sans-serif;
  --font-cn: 'Noto Sans SC', system-ui, sans-serif;
}

.home-container {
  min-height: 100vh;
  background: var(--white);
  font-family: var(--font-sans);
  color: var(--black);
}

/* Top Navigation */
.navbar {
  height: 60px;
  background: var(--black);
  color: var(--white);
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 40px;
}

.nav-brand {
  font-family: var(--font-mono);
  font-weight: 800;
  letter-spacing: 1px;
  font-size: 1.2rem;
}

.nav-links {
  display: flex;
  align-items: center;
}

.github-link {
  color: var(--white);
  text-decoration: none;
  font-family: var(--font-mono);
  font-size: 0.9rem;
  font-weight: 500;
  display: flex;
  align-items: center;
  gap: 8px;
  transition: opacity 0.2s;
}

.github-link:hover {
  opacity: 0.8;
}

.arrow {
  font-family: sans-serif;
}

/* Main Content Area */
.main-content {
  max-width: 1400px;
  margin: 0 auto;
  padding: 60px 40px;
}

/* Hero Section */
.hero-section {
  display: flex;
  justify-content: space-between;
  margin-bottom: 80px;
  position: relative;
}

.hero-left {
  flex: 1;
  padding-right: 60px;
}

.tag-row {
  display: flex;
  align-items: center;
  gap: 15px;
  margin-bottom: 25px;
  font-family: var(--font-mono);
  font-size: 0.8rem;
}

.orange-tag {
  background: var(--orange);
  color: var(--white);
  padding: 4px 10px;
  font-weight: 700;
  letter-spacing: 1px;
  font-size: 0.75rem;
}

.version-text {
  color: #999;
  font-weight: 500;
  letter-spacing: 0.5px;
}

.main-title {
  font-size: 4.5rem;
  line-height: 1.2;
  font-weight: 500;
  margin: 0 0 40px 0;
  letter-spacing: -2px;
  color: var(--black);
}

.gradient-text {
  background: linear-gradient(90deg, #000000 0%, #444444 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  display: inline-block;
}

.hero-desc {
  font-size: 1.05rem;
  line-height: 1.8;
  color: var(--gray-text);
  max-width: 640px;
  margin-bottom: 50px;
  font-weight: 400;
  text-align: justify;
}

.hero-desc p {
  margin-bottom: 1.5rem;
}

.highlight-bold {
  color: var(--black);
  font-weight: 700;
}

.highlight-orange {
  color: var(--orange);
  font-weight: 700;
  font-family: var(--font-mono);
}

.highlight-code {
  background: rgba(0, 0, 0, 0.05);
  padding: 2px 6px;
  border-radius: 2px;
  font-family: var(--font-mono);
  font-size: 0.9em;
  color: var(--black);
  font-weight: 600;
}

.slogan-text {
  font-size: 1.2rem;
  font-weight: 520;
  color: var(--black);
  letter-spacing: 1px;
  border-left: 3px solid var(--orange);
  padding-left: 15px;
  margin-top: 20px;
}

.blinking-cursor {
  color: var(--orange);
  animation: blink 1s step-end infinite;
  font-weight: 700;
}

@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}

.decoration-square {
  width: 16px;
  height: 16px;
  background: var(--orange);
}

.hero-right {
  flex: 0.8;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: flex-end;
}

.logo-container {
  width: 100%;
  display: flex;
  justify-content: flex-end;
  padding-right: 40px;
}

.hero-logo {
  max-width: 500px; /* Adjust logo size */
  width: 100%;
}

.scroll-down-btn {
  width: 40px;
  height: 40px;
  border: 1px solid var(--border);
  background: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  color: var(--orange);
  font-size: 1.2rem;
  transition: all 0.2s;
}

.scroll-down-btn:hover {
  border-color: var(--orange);
}

/* Dashboard Two-Column Layout */
.dashboard-section {
  display: flex;
  gap: 60px;
  border-top: 1px solid var(--border);
  padding-top: 60px;
  align-items: flex-start;
}

.dashboard-section .left-panel,
.dashboard-section .right-panel {
  display: flex;
  flex-direction: column;
}

/* Left Panel */
.left-panel {
  flex: 0.8;
}

.panel-header {
  font-family: var(--font-mono);
  font-size: 0.8rem;
  color: #999;
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 20px;
}

.status-dot {
  color: var(--orange);
  font-size: 0.8rem;
}

.section-title {
  font-size: 2rem;
  font-weight: 520;
  margin: 0 0 15px 0;
}

.section-desc {
  color: var(--gray-text);
  margin-bottom: 25px;
  line-height: 1.6;
}

.metrics-row {
  display: flex;
  gap: 20px;
  margin-bottom: 15px;
}

.metric-card {
  border: 1px solid var(--border);
  padding: 20px 30px;
  min-width: 150px;
}

.metric-value {
  font-family: var(--font-mono);
  font-size: 1.8rem;
  font-weight: 520;
  margin-bottom: 5px;
}

.metric-label {
  font-size: 0.85rem;
  color: #999;
}

/* Project Simulation Steps */
.steps-container {
  border: 1px solid var(--border);
  padding: 30px;
  position: relative;
}

.steps-header {
  font-family: var(--font-mono);
  font-size: 0.8rem;
  color: #999;
  margin-bottom: 25px;
  display: flex;
  align-items: center;
  gap: 8px;
}

.diamond-icon {
  font-size: 1.2rem;
  line-height: 1;
}

.workflow-list {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.workflow-item {
  display: flex;
  align-items: flex-start;
  gap: 20px;
}

.step-num {
  font-family: var(--font-mono);
  font-weight: 700;
  color: var(--black);
  opacity: 0.3;
}

.step-info {
  flex: 1;
}

.step-title {
  font-weight: 520;
  font-size: 1rem;
  margin-bottom: 4px;
}

.step-desc {
  font-size: 0.85rem;
  color: var(--gray-text);
}

/* Right Interaction Console */
.right-panel {
  flex: 1.2;
}

.console-box {
  border: 1px solid #CCC; /* Outer solid line */
  padding: 8px; /* Inner padding creates double border effect */
}

.console-section {
  padding: 20px;
}

.console-section.btn-section {
  padding-top: 0;
}

.console-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 15px;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  color: #666;
}

.upload-zone {
  border: 1px dashed #CCC;
  height: 200px;
  overflow-y: auto;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.3s;
  background: #FAFAFA;
}

.upload-zone.has-files {
  align-items: flex-start;
}

.upload-zone:hover {
  background: #F0F0F0;
  border-color: #999;
}

.upload-placeholder {
  text-align: center;
}

.upload-icon {
  width: 40px;
  height: 40px;
  border: 1px solid #DDD;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 15px;
  color: #999;
}

.upload-title {
  font-weight: 500;
  font-size: 0.9rem;
  margin-bottom: 5px;
}

.upload-hint {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  color: #999;
}

.file-list {
  width: 100%;
  padding: 15px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.file-item {
  display: flex;
  align-items: center;
  background: var(--white);
  padding: 8px 12px;
  border: 1px solid #EEE;
  font-family: var(--font-mono);
  font-size: 0.85rem;
}

.file-name {
  flex: 1;
  margin: 0 10px;
}

.remove-btn {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.2rem;
  color: #999;
}

.console-divider {
  display: flex;
  align-items: center;
  margin: 10px 0;
}

.console-divider::before,
.console-divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: #EEE;
}

.console-divider span {
  padding: 0 15px;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: #BBB;
  letter-spacing: 1px;
}

.input-wrapper {
  position: relative;
  border: 1px solid #DDD;
  background: #FAFAFA;
}

.code-input {
  width: 100%;
  border: none;
  background: transparent;
  padding: 20px;
  font-family: var(--font-mono);
  font-size: 0.9rem;
  line-height: 1.6;
  resize: vertical;
  outline: none;
  min-height: 150px;
}

.model-badge {
  position: absolute;
  bottom: 10px;
  right: 15px;
  font-family: var(--font-mono);
  font-size: 0.7rem;
  color: #AAA;
}

.start-engine-btn {
  width: 100%;
  background: var(--black);
  color: var(--white);
  border: none;
  padding: 20px;
  font-family: var(--font-mono);
  font-weight: 700;
  font-size: 1.1rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  cursor: pointer;
  transition: all 0.3s ease;
  letter-spacing: 1px;
  position: relative;
  overflow: hidden;
}

/* Clickable State (Non-disabled) */
.start-engine-btn:not(:disabled) {
  background: var(--black);
  border: 1px solid var(--black);
  animation: pulse-border 2s infinite;
}

.start-engine-btn:hover:not(:disabled) {
  background: var(--orange);
  border-color: var(--orange);
  transform: translateY(-2px);
}

.start-engine-btn:active:not(:disabled) {
  transform: translateY(0);
}

.start-engine-btn:disabled {
  background: #E5E5E5;
  color: #999;
  cursor: not-allowed;
  transform: none;
  border: 1px solid #E5E5E5;
}

/* Guidance Animation: Subtle Border Pulse */
@keyframes pulse-border {
  0% { box-shadow: 0 0 0 0 rgba(0, 0, 0, 0.2); }
  70% { box-shadow: 0 0 0 6px rgba(0, 0, 0, 0); }
  100% { box-shadow: 0 0 0 0 rgba(0, 0, 0, 0); }
}

/* Responsive Adaptation */
@media (max-width: 1024px) {
  .dashboard-section {
    flex-direction: column;
  }
  
  .hero-section {
    flex-direction: column;
  }
  
  .hero-left {
    padding-right: 0;
    margin-bottom: 40px;
  }
  
  .hero-logo {
    max-width: 200px;
    margin-bottom: 20px;
  }
}
</style>
